name = "Bigspring Light Hugo"
license = "MIT"
licenselink = "https://github.com/gethugothemes/bigspring-light-hugo/blob/main/LICENSE"
description = "Bigspring Light is a free Hugo theme built for SaaS marketing websites and digital agencies who need a fast, secure, and professional web presence."
homepage = "https://github.com/gethugothemes/bigspring-light-hugo/"
demosite = "https://bigspring-light-hugo.vercel.app/"
min_version = "0.156.0"

tags = [
  "blog",
  "responsive",
  "minimal",
  "light",
  "multilingual",
  "landing",
  "contact",
  "company",
  "tailwind",
]

features = [
  "Multilingual",
  "Taxonomies",
]

[author]
name = "Gethugothemes"
homepage = "https://gethugothemes.com"
